---
  
  - name: Adição do repositório PPA do PHP 7.4
    apt_repository:
      repo: ppa:ondrej/php
      state: present 

  - name: Instalação do Nginx e dos pacotes PHP para o funcionamento do WordPress
    apt:
      update_cache: yes
      pkg:
        - nginx
        - unzip
        - php7.4
        - php7.4-cli
        - php7.4-fpm
        - php7.4-mbstring
        - php7.4-xml
        - php7.4-mysql
        - php7.4-common
        - php7.4-gd
        - php7.4-json
        - php7.4-zip
        - php-imagick
        - php7.4-curl
        - php7.4-bcmath
    become: true
      #  update_cache: yes

  - name: Configuração do vhost nginx
    template:
      src: vhost.nginx.conf.j2
      dest: /etc/nginx/sites-enabled/default
        
  - name : Baixando o projeto do wordpress e descopactando
    ansible.builtin.unarchive:
      src: https://wordpress.org/latest.zip
      dest: /var/www/html
      remote_src: yes

  - name: Alterando o arquivo wp-config
    template:
      src: wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php
   
  - name: Alterando permissão da pasta /var/www/html/wordpress
    ansible.builtin.file:
      path: /var/www/html/wordpress
      owner: www-data
      group: www-data
      mode: '0755'

  - name: restarted nginx
    ansible.builtin.sysvinit:
      name: nginx
      state: restarted    
 
  - name: restarted php7.4-fpm
    ansible.builtin.sysvinit:
      name: php7.4-fpm
      state: restarted

        # - name: Restart Nginx and Check Status
        # ansible.builtin.service:
        # name: nginx
        # state: restarted
        # register: nginx_restart_result

        # - debug:
        # var: nginx_restart_result

        #  - name: Verificar o estado atual do serviço nginx (depuração)
        # ansible.builtin.service:
        # name: nginx
        #  register: nginx_status

        # - debug:
        #  var: nginx_status


# Outras tarefas relacionadas ao WordPress podem seguir aqui.

